import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
        backgroundColor:'white',
        flex:1,
    },
    viewUserinfo:{
        // backgroundImage:'linear-gradient(to bottom, #204e8e 15%,#1a4175 30%,#15345e 40%, #0f2643 50%,#000000 100%)',
        backgroundColor:'#0f2643',
        padding:10,
        height: 'auto',
        flexDirection:'column',
        justifyContent:'space-around',
        height:320,
    },
    ImgUserAvatar:{
        height:100,
        width:100,
        borderRadius: 100,
    },
    btnEdit:{
        width:80,
        height:40,
        borderRadius:40,
        borderWidth:1,
        justifyContent:'center',
        alignItems:'center',
        marginTop:10,
        borderColor:'white'
    },
    textEdit:{
        color:'white',
        fontSize:17,
    },
    textUsername:{
        fontWeight:'bold',
        fontSize:20,
        color:'white'
    },
    textBold:{
        fontSize:14,
        fontWeight:'bold',
        color:'white'
    },
    textBasic:{
        fontSize:13,
        color:'white'
    },
    btnAddSocial:{
        height:30,
        width: 150,
        borderWidth:1,
        borderRadius: 15,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#242424',
        marginTop:5,
    },
    viewTab:{
        height:50,
        flexDirection: 'row',
        justifyContent:'space-around',
        borderBottomWidth:5,            
        borderBottomColor:'#f1f3f5'
    },
    btnTab:{
        width:'33%',
        height:50,
        justifyContent:'center',
        alignItems:'center'
    },
    textTab:{
        fontWeight: 'bold',
        fontSize:17,
    },

    viewTabPost:{
        flexDirection:'column',
        flex:1,
    },
    viewTabComments:{
        flexDirection:'column',
        flex:1,
    },
    
    viewTabAbout:{
        flexDirection:'column',
        flex:1,
    },
    viewAboutKarma:{
        flexDirection:'row',
        height: 70,
        padding:10,
    },
    viewAboutKarmaDetail:{
        flexDirection:'column',
        height:40,
        width:'50%',
        justifyContent:'space-around'
    },
    viewAboutIntro:{
        padding:10,

    },
    textNumberKarma:{
        fontSize:16,
        fontWeight:'bold',

    },
    textKarma:{
        fontSize:14,
        color:'gray'
    },
    textAboutIntro:{
        fontWeight:'bold',
        fontSize:17,
        color:'#333333'
    },
    viewTrophyTitle:{
        backgroundColor:'#f1f3f5',
        height:30,
        justifyContent:'center',
        paddingLeft:10,
    },
    textTrophyTitle:{
        fontSize:13,
        fontWeight:'bold',
        color:'gray'
    },
    viewTrophies:{
        height:100,
        backgroundColor:'white'
    },
    textCommentTitle:{
        fontSize:16,
        fontWeight:'500'
    },
    textCommentContent:{
        fontSize:13,
        color:'gray'
    },
    imgLikeComment:{
        height:10,
        width:10,
    },
    viewCommentContainer:{
        flexDirection: 'column',
        borderBottomWidth:1,
        borderColor:'gray',
        padding:10,
        flex:1
    },
    viewCommentIntro:{
        flexDirection:'row',
    },
    viewPostContainer:{
        flexDirection:'column',
        padding:10,
        borderBottomWidth:1,
        borderColor:'gray',
        padding:10,
        flex:1
    },
    viewPostInfo:{
        flexDirection:'row',
        alignItems:'center',
        height:35,
    },
    imgPostAvatar:{
        width:20,
        height:20,
    },
    textPostCommunity:{
        fontSize:13,
        fontWeight:'bold',
    },
    textPostTime:{
        fontSize:13,
        color:'gray'
    },
    textPostTitle:{
        fontSize:17,
        fontWeight:'bold'
    },
    textPostContent:{
        fontSize:14,
        color:'gray'
    },
    viewPostButton:{
        flexDirection:'row',
        width:'60vw',    
        height:25,   
        alignItems:'flex-end'        
    },
    viewBtnTab:{
        flexDirection:'row',
        marginRight:15
    },
    btnIcon:{
        width:21,
        height:21,
        marginRight:7,
        marginLeft:7,
    },
    textPostBtn:{
        fontSize:15,
        fontWeight:'bold',
        color:'gray'
    }

})